spring:
  datasource:
    url: jdbc:mysql://localhost:3306/evo_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  output:
    ansi:
      enabled: ALWAYS

  jackson:
    default-property-inclusion: non_null

jwt:
  secret: 3Dlkc92nc73NSDkfj29fKsd83MSkcmxlsdfRklwJ2
  expiration: 172800000 # 2 days

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 0000000000000000000000000000000
#            client-secret: 000000000000000000000000000000000000
#            scope:
#              - email
#              - profile
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
#
#          facebook:
#            client-id: 00000000000000000
#            client-secret: 000000000000000000000000000000
#            scope:
#              - email
#              - public_profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
